filebeat.prospectors:
- type: log
  paths:
    - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: http://kibana:5601

output.elasticsearch:
  hosts: ["http://nginx:9200"]
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"